################################################################################
#
#   Section: 
#
################################################################################
Fabric:
  # path to fabric-folder where bin and config subfolders exist
  Path: /mnt/user/appdata/fabric
Docker:
  Network:
    Name: jedo-network
    Subnet: 172.25.0.0/16
  Container:
    Wait: 20 # Max waiting time in seconds to start a docker container prior to exit
    FabricTools: fabric-tools-container # Name of Fabric-Tools Docker Container, togengen must be available
Network: # Make sure every server and ip is set in DNS or /etc/hosts
  CA:
    # Name: localhost
    Name: ca.jenziner.jedo.test
    IP: 172.25.0.2
    Port: 7054
    Admin:
      Name: admin
      Pass: Test1
  Orderers:
    - Name: orderer.jenziner.jedo.test
      IP: 172.25.0.11
      Port: 7050
      Admin:
        Name: admin
        Pass: Test1
        Org:
          Name: JenzinerOrg
          MSP: JenzinerOrg
  Peers:
    - Name: peer0.jenziner.jedo.test
      IP: 172.25.0.21
      Port1: 8051
      Port2: 8052
      Admin:
        Name: admin
        Pass: Test1
        Org: 
          Name: JenzinerOrg
          MSP: JenzinerOrgMSP
      DB: 
        Name: db0.jenziner.jedo.test
        IP: 172.25.0.22
        Port: 8084
        Admin:
          Name: admin
          Pass: Test1
      CLI: true # true, if CLI-Container should be installed
    - Name: peer1.jenziner.jedo.test
      IP: 172.25.0.31
      Port1: 9051
      Port2: 9052
      Admin:
        Name: admin
        Pass: Test1
        Org:
          Name: JenzinerOrg
          MSP: JenzinerOrgMSP
      DB: 
        Name: db1.jenziner.jedo.test
        IP: 172.25.0.32
        Port: 9084
        Admin:
          Name: admin
          Pass: Test1
      CLI: true
  FSCs: # Names must be according Auditor, Issuers, Users
    - Name: aud
      Pass: Test1
      Owner: auditor
    - Name: iss
      Pass: Test1
      Owner: issuer
    - Name: Worb
      Pass: Test1
      Owner: Worb
    - Name: Biglen
      Pass: Test1
      Owner: Biglen
  Auditors:
    - Name: aud
      Pass: Test1
      Owner: auditor
  Issuers:
    - Name: iss
      Pass: Test1
      Owner: issuer
  Users:
    - Name: do
      Pass: Test1
      Owner: Worb
    - Name: ra
      Pass: Test1
      Owner: Worb
    - Name: lu
      Pass: Test1
      Owner: Biglen
    - Name: is
      Pass: Test1
      Owner: Biglen
  
