################################################################################
#
#   Section: 
#
################################################################################
Fabric:
  # path to fabric-folder where bin and config subfolders exist
  Path: /mnt/user/appdata/fabric
Docker:
  Network:
    Name: jedo-network
    Subnet: 172.25.0.0/16
    Gateway: 172.25.0.1
  Container:
    Wait: 20 # Max waiting time in seconds to start a docker container prior to exit
    FabricTools: fabric-tools-container # Name of Fabric-Tools Docker Container, togengen must be available
FabricNetwork: # Make sure every server and ip is set in DNS or /etc/hosts
  RootCA:
    Name: ca.jedo.test
    Pass: Test1
    IP: 172.25.0.5
    Port: 6040
    OpPort: 6049
    OpenSSL: false
  Channel: eu-jedo-test
  Organizations:
    - Name: JenzinerOrg
      Consortium: JEDO # Name of consortium if member or null
      CA:
        Name: ca.jenziner.jedo.test
        Pass: Test1
        IP: 172.25.1.5
        Port: 7040
        OpPort: 7049
        OpenSSL: false
        Ext:
      CAAPI:
        Name: api.ca.jenziner.jedo.test
        IP: 172.25.1.6
        Port: 7047
        SrvPort: 7048
      Admin:
        Name: admin.jenziner.jedo.test
        Pass: Test1
      Orderers:
        - Name: orderer.jenziner.jedo.test
          Pass: Test1
          IP: 172.25.1.11
          Port: 7051
          ClusterPort: 7052
          OpPort: 7059
      Peers: # first peer will be used as AnchorPeer
        - Name: peer0.jenziner.jedo.test
          Pass: Test1
          IP: 172.25.1.12
          Port1: 7061
          Port2: 7062
          OpPort: 7069
          CLI: 172.25.1.14
          DB: 
            Name: db.peer0.jenziner.jedo.test
            Pass: Test1
            IP: 172.25.1.13
            Port: 7064
        - Name: peer1.jenziner.jedo.test
          Pass: Test1
          IP: 172.25.1.15
          Port1: 7071
          Port2: 7072
          OpPort: 7079
          CLI: 172.25.1.17
          DB: 
            Name: db.peer1.jenziner.jedo.test
            Pass: Test1
            IP: 172.25.1.16
            Port: 7074
    - Name: LiebiwilerOrg
      Consortium: # Name of consortium if member or null
      CA:
        Name: ca.liebiwiler.jedo.test
        Pass: Test1
        IP: 172.25.2.5
        Port: 8040
        OpPort: 8049
        OpenSSL: false
        Ext:
      CAAPI:
        Name: api.ca.liebiwiler.jedo.test
        IP: 172.25.2.6
        Port: 8047
        SrvPort: 8048
      Admin:
        Name: admin.liebiwiler.jedo.test
        Pass: Test1
      Orderers:
        - Name: orderer.liebiwiler.jedo.test
          Pass: Test1
          IP: 172.25.2.11
          Port: 8051
          ClusterPort: 8052
          OpPort: 8059
      Peers: # first peer will be used as AnchorPeer
        - Name: peer0.liebiwiler.jedo.test
          Pass: Test1
          IP: 172.25.2.12
          Port1: 8061
          Port2: 8062
          OpPort: 8069
          CLI: 172.25.2.14
          DB: 
            Name: db.peer0.liebiwiler.jedo.test
            Pass: Test1
            IP: 172.25.2.13
            Port: 8064
    - Name: BreitschiOrg
      Consortium: # Name of consortium if member or null
      CA:
        Name:
        Pass: 
        IP:
        Port:
        OpPort:
        OpenSSL: false
        Ext: ca.jenziner.jedo.test
      CAAPI:
        Name: 
        IP: 
        Port: 
        SrvPort:
      Admin:
        Name: admin.breitschi.jedo.test
        Pass: Test1
      Orderers:
        - Name: orderer.breitschi.jedo.test
          Pass: Test1
          IP: 172.25.3.11
          Port: 9051
          ClusterPort: 9052
          OpPort: 9059
      Peers: # first peer will be used as AnchorPeer
        - Name: peer0.breitschi.jedo.test
          Pass: Test1
          IP: 172.25.3.12
          Port1: 9061
          Port2: 9062
          OpPort: 9069
          CLI: 172.25.3.14
          DB: 
            Name: db.peer0.breitschi.jedo.test
            Pass: Test1
            IP: 172.25.3.13
            Port: 9064
TokenNetwork:
  Name: eu.jedo.test
  FSCs: # Names must be according Auditor, Issuers, Users
    - Name: aud
      Pass: Test1
      Owner: auditor
    - Name: iss
      Pass: Test1
      Owner: issuer
    - Name: Worb
      Pass: Test1
      Owner: Worb
    - Name: Biglen
      Pass: Test1
      Owner: Biglen
  Auditors:
    - Name: aud
      Pass: Test1
      Owner: auditor
  Issuers:
    - Name: iss
      Pass: Test1
      Owner: issuer
  Users:
    - Name: do
      Pass: Test1
      Owner: Worb
    - Name: ra
      Pass: Test1
      Owner: Worb
    - Name: lu
      Pass: Test1
      Owner: Biglen
    - Name: is
      Pass: Test1
      Owner: Biglen
  
